export const ROUTES = {
  SPLASH: 'Splash',
  LOADING: 'Loading',
  LANGUAGE: 'LanguageSelection',
  MOBILE_LOGIN: 'MobileLogin',
  SIGNUP: 'Signup',
  QR_CODE: 'QRCode',
  SET_MPIN: 'SetMPIN',
  MPIN_LOGIN: 'MPINLogin',
  APP: 'App',
  DRAWER: 'Drawer',
  TABS: 'Tabs',
  DASHBOARD: 'Dashboard',
  LOADS: 'CustomerLoadRequestList',
  PAYMENT: 'Payment',
  PROFILE: 'Profile',
  PAYMENT_OTP: 'PaymentOTPGeneration',
  VERIFY_PAYMENT_OTP: 'VerifyPaymentOTP',
  FREIGHT_PAYMENT: 'FreightPayment',
  CUSTOMER_LOADS: 'CustomerLoadRequestList',
};
