// src/events/events.ts

export const EVENTS = {
  OPEN_WAITING_LOADER: 'OPEN_WAITING_LOADER',
  CLOSE_WAITING_LOADER: 'CLOSE_WAITING_LOADER',

  DRIVER_ACCEPTED: 'DRIVER_ACCEPTED',
  DRIVER_REJECTED: 'DRIVER_REJECTED',

  LOCATION_UPDATED: 'LOCATION_UPDATED',
} as const;
